name: Security CI

on:
  push:
    branches: [ "dev" ]

  
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: requirements.txt
          
      - name: Bandit
        run: | 
          pip3 install -r requirements.txt 
          bandit -r src/ -lll -f json -o report_bandit.json
        
      - name: Publicar relatório de segurança
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: report_bandit.json

  build-and-scan:
    runs-on: ubuntu-latest
    depends-on: security-scan
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Trivy + Docker Build
        run: docker build -t calculadora:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'calculadora:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'