name: Security CI

on:
  push:
    branches: [ "dev" ]

  
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - name: Bandit
        uses: pyupio/action-bandit@v1
        with:
          args: -r src/ --format json --output-file report-bandit.json