name: Security CI

on:
  push:
    branches: [ "dev" ]

  
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: GitLeaks
        run: docker run --rm -v $(pwd):/repo zricethezav/gitleaks:latest detect --source /repo --report-path /repo/leaks.json

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: leaks
          path: leaks.json